services:
  web:
    build: .
    entrypoint: sh ./launch.sh
    command: gunicorn --bind 0.0.0.0:8000 dev_hub.wsgi:application
    volumes:
      - .:/app
    environment:
      DEV_HUB_DJANGO_SECRET: ${DEV_HUB_DJANGO_SECRET}
      DEV_HUB_DEBUG: ${DEV_HUB_DEBUG}
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: always