services:
  web:
    build: .
    entrypoint: sh ./launch.sh
    command: gunicorn --bind 0.0.0.0:8000 dev_hub.wsgi:application
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles  # Mount static files
    environment:
      DEV_HUB_DJANGO_SECRET: ${DEV_HUB_DJANGO_SECRET}
      DEV_HUB_DEBUG: ${DEV_HUB_DEBUG}
      DEV_HUB_ALLOWED_HOSTS: ${DEV_HUB_ALLOWED_HOSTS}
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:latest
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./staticfiles:/app/staticfiles  # Serve collected static files
      - /etc/letsencrypt/live/${DOMAIN}:/etc/letsencrypt/live/${DOMAIN}:ro
      - /etc/letsencrypt/archive/${DOMAIN}:/etc/letsencrypt/archive/${DOMAIN}:ro
      - /etc/letsencrypt/keys:/etc/letsencrypt/keys:ro
    depends_on:
      - web
    restart: always
  
networks:
  default:
    name: dev_hub

volumes:
  static_volume: