services:
  web:
    build: .
    entrypoint: sh ./launch.sh
    command: gunicorn --bind 0.0.0.0:8000 dev_hub.wsgi:application
    volumes:
      - .:/app
      # - static_volume:/app/staticfiles  # Mount static files
      - ./staticfiles:/app/staticfiles  # Mount static files
    environment:
      DEV_HUB_DJANGO_SECRET: ${DEV_HUB_DJANGO_SECRET}
      DEV_HUB_DEBUG: ${DEV_HUB_DEBUG}
      DEV_HUB_ALLOWED_HOSTS: ${DEV_HUB_ALLOWED_HOSTS}
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles  # Serve collected static files
    depends_on:
      - web
    restart: always
  
networks:
  default:
    name: dev_hub

volumes:
  static_volume: