on:
  push:
    branches:
      - '**' # Runs on push to any branch
  pull_request: # Runs when a PR is created or updated

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DEV_HUB_DJANGO_SECRET: ${{ secrets.DEV_HUB_DJANGO_SECRET }}
      DEV_HUB_DEBUG: ${{ secrets.DEV_HUB_DEBUG }}
      DEV_HUB_ALLOWED_HOSTS: localhost,127.0.0.1
      ACCEPTANCE_TEST_SERVER_URL: http://localhost

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Create .env file locally
        run: |
          echo "DEV_HUB_DJANGO_SECRET=${{ secrets.DEV_HUB_DJANGO_SECRET }}" > .env
          echo "DEV_HUB_DEBUG=${{ secrets.DEV_HUB_DEBUG }}" >> .env
          echo "DEV_HUB_ALLOWED_HOSTS=${{ vars.DEV_HUB_ALLOWED_HOSTS }}" >> .env

      - name: Build Local Application
        run: |
          docker compose up -d --build
      
      - name: Run Django Tests
        run: |
          python manage.py test

